### PR TITLE
Fix build with Flutter 3.16.

### LINKED ISSUE #62: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
After upgrading flutter version to `3.10`, following errors occured. Please fix it asap:
```
Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
editor.dart:714
 - TextInputClient.insertContent
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:1117:8: Context: 'TextInputClient.insertContent' is defined here.
  void insertContent(KeyboardInsertedContent content) {}
       ^^^^^^^^^^^^^
: Error: Type 'DragSelectionUpdateCallback' not found.
text_selection.dart:1069
  final DragSelectionUpdateCallback? onDragSelectionUpdate;

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: 'DragSelectionUpdateCallback' isn't a type.
text_selection.dart:1069
  final DragSelectionUpdateCallback? onDragSelectionUpdate;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: No named parameter with the name 'kind'.
text_selection.dart:1250
            debugOwner: this, kind: PointerDeviceKind.touch),
                              ^^^^
/C:/flutter/packages/flutter/lib/src/gestures/long_press.dart:248:3: Context: Found this candidate, but the arguments don't match.
  LongPressGestureRecognizer({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: No named parameter with the name 'kind'.
text_selection.dart:1268
            debugOwner: this, kind: PointerDeviceKind.mouse),
                              ^^^^
```

### LINKED ISSUE #66: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
Hello, I'd like to ask for help.

My Flutter version is 3.16.0 
dart version is 3.2.0

I executed this command

`flutter build apk --release --target-platform=android-arm64`

스크린샷 2023-11-24 오후 8 29 22

And this error message occurred.

How can we resolve this? I really need your help

### PR DESCRIPTION
**Pull request by Cyp**
Also, bump version to 1.6.0.

Fixes #66.

Also, should probably close #62, since it was fixed already.

### CODE REVIEW

**Comment by dthuering** [comment]
Looks good, I forgot to open my own MR for https://github.com/glynskyi/zefyrka/compare/main...webmobix:zefyrka:feature/add-missing-delegate-methods
Compiles successfully again.

**Comment by goodhare** [comment]
Yup! Looks good lets merge it! :)

**Comment by walkerJung** [comment]
plz merge it!

**Comment by Dampfwalze** [comment]
@glynskyi @featzima Without this PR no one can build this package. This should be merged ASAP.

**Comment by featzima** [comment]
Aligned the code with latest Flutter version Flutter version with the latest 3.19 and published as [zefyrka:1.6.0](https://pub.dev/packages/zefyrka/changelog#160)

**Pull request closed without merging**
