### PR TITLE
Quickfix for newer flutter version

### PR DESCRIPTION
**Pull request by bartoszpijet**
Just an empty handler for some mac/ios functions.

### CODE REVIEW

**Review by SahajRana — COMMENTED** [review]
Please also add 

```
@override
  void didChangeInputControl(
      TextInputControl? oldControl, TextInputControl? newControl) {}
```
to cover the latest Flutter Master Build as well

**Comment by bartoszpijet** [comment]
> Please also add
> 
> ```
> @override
>   void didChangeInputControl(
>       TextInputControl? oldControl, TextInputControl? newControl) {}
> ```
> 
> to cover the latest Flutter Master Build as well

Pushed changes to my fork. Thanks for the reminder.

**Comment by leconio** [comment]
@glynskyi pls merge this request.I can't build it on newer flutter. thanks
image

**Comment by featzima** [comment]
pushed [1.4.0 version](https://pub.dev/packages/zefyrka) with Flutter 3.7 compatibility

**Pull request closed without merging**
